version: '3.8'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    environment:
      - NGINX_PORT=80
