name: Deploy to Docker registry

on:
  push:
    branches: [production]

jobs:
  main:
    env:
      commitmsg: ${{ github.event.pull_request.title}}
      commitsha: ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: shmidtelson/yaroshenko-frontend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
