name: Deploy to Docker registry

on:
  pull_request:
    types: [closed]
    branches: [production]

jobs:
  main:
    env:
      commitmsg: ${{ github.event.pull_request.title}}
      commitsha: ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: shmidtelson/yaroshenko-frontend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: Sending info about updating to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Изменения успешно добавлены на сайт:</b>  <code>${{ env.commitmsg }}</code>

            sha: ${{ env.commitsha }}
