name: Deploy to Docker registry

on:
  pull_request:
    types: [closed]
    branches: [production]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: shmidtelson/yaroshenko-frontend:latest
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: Logging
        run: |
          # Get last commit message
          readonly local last_commit2_log=$(git log --format=%B -n 1 -skip 1 ${{ github.event.after }})
          echo "last commit 2  log: $last_commit2_log"

          readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )
          echo "number of occurence of '$COMMIT_FILTER' in '$last_commit_log': $filter_count"

      - name: Sending info about updating to telegram
        uses: appleboy/telegram-action@master
        with:
          to: 188118870
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Изменения успешно добавлены на сайт:</b> <code>${{ env.commitmsg }}</code>

            sha: ${{ env.commitsha }}
