name: Test workflow

on:
  push:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send info about update
        uses: appleboy/telegram-action@master
        with:
          to: 188118870
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>Новые изменения:</b> <code>${{ github.event.pull_request.base.message }}</code> (${{ github.event.pull_request.base.sha }})
